changesetBaseRefs:
  - develop

initFields:
  exports:
    .:
      import: ./dist/index.js
      types: ./dist/index.d.ts
  main: dist/index.js
  private: true
  scripts:
    build: tsc --build
    clean: rimraf build dist *.tsbuildinfo **/*.tsbuildinfo
    test: mocha --config ../../config/.mocharc.cjs
    'test:dev': mocha --config ../../config/.mocharc.cjs --forbid-only=false --parallel=false --timeout=9999999999
    watch: tsc --build --watch
  type: module
  types: dist/index.d.ts

initScope: bscotch

nodeLinker: pnpm

packageExtensions:
  '@electron-forge/maker-base@*':
    dependencies:
      electron-winstaller: ^5.1.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
